name: Manufacturing Tests

on:
  pull_request:
    branches:
     - '**'
  workflow_dispatch:

jobs:
  mfg_test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: true
        submodules: recursive
    
    - name: Compile application
      id: compile
      uses: particle-iot/compile-action@v1
      with:
          particle-platform-name: 'tracker'
          device-os-version: '5.3.0'
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}

    - name: Put Device in DFU Mode
      id: dfu
      run: |
        particle usb dfu
    
    - name: Flash Device
      id: flash
      run: |
        particle flash --usb ${{ steps.compile.outputs.firmware-path }}
    
    - name: Wait for Device Initialization
      run: sleep 30
    
    - name: Run Manufacturing Tests
      id: mfg_test
      run: python3 run_mfg_test.py

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mfg_test_results
        path: mfg_test_results.log
        retention-days: 7

        
      
      